package com.example.ragApp.helper;

public enum UseCaseType {
    BUSINESS_FINANCE_ADVICE,
    PREPARE_BANK_LOAN,
    ELIGIBILITY_CHECKER,
    CAPITAL_DEPLOYMENT,
    REVIEW_BALANCE_SHEET,
    SCALE_UP_PLAN,
    MARKETING_GROWTH,
    HR_EFFICIENCY,
    EXPORT_PROCESS,
    IMPORT_PROCESS,
    PAYMENT_RECOVERY_EMAIL
}